apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-first-comp
  description: my first component
  tags:
    - java
    - data
spec:
  type: service
  lifecycle: experimental
  owner: vincent@example.com
