apiVersion: backstage.io/v1alpha1
kind: Template
metadata:
  name: docs-template
  title: My doc template
  description: Create a new standalone documentation project
  tags:
    - recommended
    - techdocs
    - mkdocs
spec:
  owner: guest
  templater: cookiecutter
  type: documentation
  path: "."

  schema:
    required:
      - component_id
      - description
    properties:
      component_id:
        title: Name
        type: string
        description: Unique name of the component
      description:
        title: Description
        type: string
        description: Help others understand what these docs are about.
